# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9UNpAk8RsJ7VHp3O4MOE7CzUQ_10QMQ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("data_clean.csv")
data

data.info()

print(data)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import seaborn as sns

data = pd.read_csv("data_clean.csv")
data

print(type(data))
print(data.shape)
print(data.size)

data1 = data.drop(['Unnamed: 0',"Temp C"], axis =1)
data1

data1.info()

#Convert the month column data type to float data type
data1['Month']=pd.to_numeric(data['Month'],errors='coerce')
data1.info()

data1[data1.duplicated()]

data1[data1.duplicated(keep=False)]

#Drop duplicates rows
data1.drop_duplicates(keep='first',inplace=True)
data1