# -*- coding: utf-8 -*-
"""Groceries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8tfC190-82l80CPp_OcgbiyK7gtHe9x
"""

import pandas as pd
import numpy as np

data=pd.read_csv('Groceries_dataset.csv')
data

"""Observations

- there are no null values
- all columns are object type and categorical
- As the columns are categorical,we can adopt one-hot-encoding
"""

!pip install mlxtend

import pandas as pd
import mlxtend
from mlxtend.frequent_patterns import apriori,association_rules
import matplotlib.pyplot as plt

#plot a bar chart to visualie the category of class on the ship
counts = data['Member_number'].value_counts()
plt.bar(counts.index, counts.values)

#perform one-hot encoding on categorical columns
df = pd.get_dummies(data,dtype=int)
df.head()

import pandas as pd

df = pd.read_csv("Groceries_dataset.csv")
df.info()

print(df.head())

print("Columns:", df.columns.tolist())

counts = df['itemDescription'].value_counts()
plt.bar(counts.index, counts.values)

data.info()

data.head ()

import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

df.columns = df.columns.str.strip()

