# -*- coding: utf-8 -*-
"""Multiple linear regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxKOcFhIpY5X6GBtLlRVFn5YsidPJvge

ASSUMPTIONS IN MULTIPLELINEAR REGRESSION
- 1.LINEARITY: The relationship between the predictors and the response is linear.
- 2.INDEPENDENCE: Observations are independent of each other.
- 3.HOMOSCEDASTICITY: The residuals (differences blw observed and predicted values) exhibit constant variance at all levels of the predictor
- 4.NORMAL DISTRIBUTIONOF ERRORS: The residuals of the model are normally distributed
- 5.NO MULTICOLLINEARITY: The independent variables should not be too highly correlated with each other Violations of these assumptions may lead to in efficeincy in the regression parameters and unreliable predictors
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf
from statsmodels.graphics.regressionplots import influence_plot

cars=pd.read_csv("Cars.csv")
cars.head()

#rEARRANGE THE COLUMNS
cars = pd.DataFrame(cars, columns=["HP","VOL","SP","WT","MPG"])
cars.head()

"""DESCRIPTION OF COLUMNS
- HP: Horse power of car
- MPG: milege of the car
- VOL: volume of the cars(size)
- SP: Top speed of the car(Mlies per hour)
- WT: Weight of the car(ponds)
-

EDA
"""

cars.info()

#CHECK FOR MISSING VALUES
cars.isna().sum()

"""- There are no missing values
- There are 81 observations
- the data types of the columns are relevant and valid
"""

#Create a figure with two subplots (one above the other)
fig, (ax_box, ax_hist) = plt.subplots(2, sharex=True, gridspec_kw={"height_ratios": (.15, .85)})
#Creating a boxplot
sns.boxplot(data=cars, x='HP', ax=ax_box, orient='h')
ax_box.set(xlabel='') # Remove x Label for the boxplot
#Creating a histogram in the same x-axis
sns.histplot(data=cars, x='HP', ax=ax_hist, bins=30, kde=True, stat="density")
ax_hist.set(ylabel='Density')
#Adjust Layout
plt.tight_layout()
plt.show()

