# -*- coding: utf-8 -*-
"""Random_forest_classifier.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GjgJ76-hYfEQiJgsAQBNDx6yvWyoPSWg
"""

import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, StratifiedKFold

dataframe = pd.read_csv("diabetes.csv")
dataframe

from sklearn.model_selection import KFold,StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
X = dataframe.iloc[:,1:8]
Y = dataframe.iloc[:,8]
kfold=StratifiedKFold(n_splits=10,random_state=2023,shuffle=True)
model = RandomForestClassifier(n_estimators=200,random_state = 20,max_depth=None)
results=cross_val_score(model,X,Y,cv=kfold)
print(results)
print(results.mean())

