# -*- coding: utf-8 -*-
"""simple linear regression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127C1WJiYQHuz9s6bw4hqprrXxqCEC21A
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

data1 = pd.read_csv("NewspaperData.csv")
data1

data1.info()

data1.describe()

fig,axes=plt.subplots(2,1,figsize=(8,6),gridspec_kw={'height_ratios':[1,3]})
sns.boxplot(data=data1["daily"],ax=axes[0],color='skyblue',width=0.5,orient='h')
axes[0].set_title("Boxplot")
axes[0].set_xlabel("daily")
sns.histplot(data1["daily"],kde=True,ax=axes[1],color='Purple',bins=30)
axes[1].set_title("Histogram with KDE")
axes[1].set_xlabel("Daily")
axes[1].set_ylabel("Y")
plt.tight_layout()
plt.show()

plt.scatter(data1["daily"],
            data1["sunday"])



"""Scatter plot

"""

x=data1["daily"]
y=data1["sunday"]
plt.scatter(data1["daily"], data1["sunday"])
plt.xlim(0, max(x) + 100)
plt.ylim(0, max(y) + 100)
plt.show()

"""Observations
-The relationship between x(daily) and y(sunday) is seen to be linear as seen from scatter plot
-The coreelation is strong and positive with person's corelation coefficient of 0.958154
"""

import statsmodels.formula.api as smf
model1 = smf.ols("sunday~daily", data = data1).fit()

model1.summary()

"""- The predicted equation is y_hat = beta_0 + beta_1 X

- beta0 = 13.8356
- beta1 = 1.3397

- The probability (p-value) for intercept (beta_0) is 0.707 > 0.05

- Therefore the intercept coefficient may not be that much significant in prediction

- However the p-value for "daily" (beta_1) is 0.00 < 0.50

- Therefore the beta_1 coefficient is highly significant and is contribute to prediction
"""

#print the fitted line coefficients (Beta-0 and Beta-1)
model1.params

#Build regression model
import statsmodels.formula.api as smf
model1 = smf.ols("sunday~daily", data = data1).fit()

#print the quality of fitted line
(model1.rsquared,model1.rsquared_adj)

"""PREDICT FOR NEW DATA POINT"""

#PREDICT FOR 200 AND 300 DAILY CIRCULATION
newdata=pd.Series([200,300,1500])

data_pred=pd.DataFrame(newdata,columns=['daily'])
data_pred

model1.predict(data_pred)

#predict on all given training data
pred = model1.predict(data1["daily"])
pred

#Add predictedd values as a column in data1
data1["Y_hat"]=pred
data1

#Compute the error values (residuals) and add as another column
data1["residuals"]=data1["sunday"]-data1["Y_hat"]

#Compute mean square error for the model
mse = np.mean((data1["daily"]-data1["Y_hat"])**2)
rmse = np.sqrt(mse)
print("MSE: ",mse)#squared values
print("RMSE: ",rmse)#square root of squared values

"""#Checking the model residuals scatter plot"""

#plot the residulas versus y_hat (to check wheather residuals are independent of each)
plt.scatter(data1["Y_hat"], data1["residuals"])

"""Observations:
- There appears to be no trend and the residuals are randomly placed around the zero error line
- Hence the assumption of homoscedasticity is satisfied (constant varience in residuals)
"""

#plot the Q-Q plot(to check the normality of residuals)
import statsmodels.api as sm
sm.qqplot(data1["residuals"], line='45', fit=True)
plt.show()

#plot the kde disribution for residuals
sns.histplot(data1["residuals"], kde=True)

"""Observations:
- The data points are seen to closdely follow the reference line of normality
- Hence the residuals are approximately normally distributed as also can be seen from the
"""



