# -*- coding: utf-8 -*-
"""TitanicAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGPQgB8VPq0-fM_sZNLwtFGN7b-sxGRf
"""

from  google.colab import files
uploaded = files.upload()

import pandas as pd

data=pd.read_csv('Titanic.csv')
data

