# -*- coding: utf-8 -*-
"""TitanicAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TGPQgB8VPq0-fM_sZNLwtFGN7b-sxGRf
"""

from  google.colab import files
uploaded = files.upload()

import pandas as pd

data=pd.read_csv('Titanic.csv')
data

"""Observations
- there are no null values
- all columns are object type and categorical
- As the columns are categorical,we can adopt one-hot-encoding
"""

!pip install mlxtend

import pandas as pd
import mlxtend
from mlxtend.frequent_patterns import apriori,association_rules
import matplotlib.pyplot as plt

#plot a bar chart to visualie the category of class on the ship
counts = data['Class'].value_counts()
plt.bar(counts.index, counts.values)

#perform one-hot encoding on categorical columns
df = pd.get_dummies(data,dtype=int)
df.head()

df.info()

#Apply apriori algorithm to get itemsets combinations
frequent_itemsets = apriori(df, min_support=0.05, use_colnames=True, max_len=None)
frequent_itemsets

#Generate association rules with metrics
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
rules

rules.sort_values(by='lift',ascending=False)

"""Conclusion
- Adult females travelling in 1st class were among the most survived.
"""

import matplotlib.pyplot as plt
rules[['support','confidence','lift']].hist(figsize=(15,7))
plt.show()

"""Observations
- In support value frequency more than 80 at range 1.0-1.5
- In confidence value frequency is near to 40 at range 1.0
- In lift ratio the frequency is more than 100 at range between 1.0-1.5
- Max frequency is observed in lift ratio
"""

import matplotlib.pyplot as plt
plt.scatter(rules['support'], rules['confidence'])
plt.show()

"""The confidence value is increasing with increase in support"""

plt.scatter(rules['confidence'], rules['lift'])
plt.show()

,

rules.sort_values(by='confidence',ascending=False)